### ISSUE TITLE
System.OverflowException: Value was either too large or too small for an Int16

### ISSUE THREAD

**Issue by azurenekowo** [CTFAK/CTFAK2.0#92] opened 2024-01-13 05:59 UTC
Hi, I was running the "Export as MFA" option, while it threw out this error.
The game name is Splatter School, if that helps.

```
CTFAK 2.2
Execution of Sound Dumper finished in 0.0949057 seconds

Game Information:
Game Name: ???????? 1
Author:
Number of frames: 36
Fusion Build: 249

6 tool(s) available

Select tool:
0. Exit CTFAK
1. Export as MFA
2. Dump Everything
3. Image Dumper
4. Sound Dumper
5. Packed Data Dumper
6. Sorted Image Dumper
1
Selected tool: Export as MFA. Executing
[12:52:31:48] Reading Fonts
[12:52:31:48] Reading Sounds
[12:52:31:48] Reading Music
[12:52:31:48] Reading Icons
[12:52:31:71] Reading Images
[12:52:31:73] Reading MFA Chunk 33 (Frame Virtual Rect)
[12:52:31:74] Reading MFA Chunk 37 (Layer Shader Settings)
[12:52:31:74] Reading MFA Chunk 40 (Frame Shader Settings)
[12:52:31:74] Reading MFA Chunk 39 (Frame Movement Timer)
[12:52:32:05] No icon found for Platform
[12:52:32:45] Preparing to translate 36 frames
[12:52:32:49] Translating frame ???? 19 - 0
[12:52:32:49] Translating frame ???? - 1
[12:52:32:49] Translating frame 1??? - 2
[12:52:32:50] Translating frame 1?-1 - 3
[12:52:32:50] Translating frame 1?-2 - 4
[12:52:32:50] Translating frame 1?-?? - 5
[12:52:32:50] Translating frame 2??? - 6
[12:52:32:51] Translating frame 2?-1 - 7
[12:52:32:51] Translating frame 2?-2 - 8
[12:52:32:52] Translating frame 2?-3 - 9
[12:52:32:52] Translating frame 2?-?? - 10
[12:52:32:53] Translating frame 3??? - 11
[12:52:32:53] Translating frame 3?-1 - 12
[12:52:32:55] Translating frame 3?-2 - 13
[12:52:32:55] Translating frame 3?-3 - 14
[12:52:32:56] Translating frame 3?-?? - 15
[12:52:32:56] Translating frame 4??? - 16
[12:52:32:57] Translating frame 4?-1 - 17
[12:52:32:57] Translating frame 4?-2 - 18
[12:52:32:58] Translating frame 4?-3 - 19
[12:52:32:58] Translating frame 4?-?? - 20
[12:52:32:58] Translating frame 5??? - 21
[12:52:32:59] Translating frame 5?-1 - 22
[12:52:32:59] Translating frame 5?-2 - 23
[12:52:32:60] Translating frame 5?-3 - 24
[12:52:32:60] Translating frame 5?-4 - 25
[12:52:32:61] Translating frame 5?-?? - 26
[12:52:32:61] Translating frame ?????? - 27
[12:52:32:61] Translating frame ??????? - 28
[12:52:32:62] Translating frame ??? - 29
[12:52:32:62] Translating frame ??????-??? - 30
[12:52:32:63] Translating frame op - 31
[12:52:32:63] Translating frame CG??? - 32
[12:52:32:63] Translating frame ???????? - 33
[12:52:32:64] Translating frame ????? - 34
[12:52:32:65] Translating frame ?????2 - 35
pos: 22
pos: 62
pos: 6192
pos: 6232
[12:52:41:88] System.OverflowException: Value was either too large or too small for an Int16.
   at System.Convert.ThrowInt16OverflowException()
   at CTFAK.MMFParser.EXE.Loaders.Events.Parameters.Group.generateChecksum(String name, String pass) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Group.cs:line 32
   at CTFAK.MMFParser.EXE.Loaders.Events.Parameters.Group.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Group.cs:line 71
   at CTFAK.CCN.Chunks.Frame.Parameter.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Events.cs:line 520
   at CTFAK.CCN.Chunks.Frame.Condition.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Events.cs:line 408
   at CTFAK.CCN.Chunks.Frame.EventGroup.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Events\Events.cs:line 338
   at CTFAK.MFA.MFAEvents.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\MFA\MFAEvents.cs:line 203
   at CTFAK.MFA.MFAFrame.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\MFA\MFAFrame.cs:line 129
   at CTFAK.MFA.MFAData.Write(ByteWriter Writer) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\MFA\MFAData.cs:line 285
   at CTFAK.Tools.FTDecompile.Execute(IFileReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Plugins\CTFAK.Decompiler\FTDecompile.cs:line 608
   at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK.Cli\Program.cs:line 233
```

**Comment by AITYunivers** [comment] 2024-01-20 01:14
MMF2 is not officially supported
Marking as duplicate of #16

**Closed by AITYunivers** 2024-01-20 01:14 UTC
