### ISSUE TITLE
Errors out when reading "Ultra Fight Da! Kyanta 2": Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by FireyCirno** [CTFAK/CTFAK2.0#80] opened 2023-10-10 07:53 UTC
Error:
`﻿System.NullReferenceException
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at CTFAK.CCN.Chunks. Frame.Frame.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\Chunks\Frame\Frame.cs:line 235 at CTFAK.CCN.GameData.Read(ByteReader reader) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\CCN\GameData.cs:line 371
at CTFAK.EXE.CCNFileReader.LoadGame(String gamePath) in D:\a\CTFAK2.0\CTFAK2.0\Core\CTFAK.Core\FileReaders\CCNFileReader.cs:line 29
at Program.Main(String[] args) in D:\a\CTFAK2.0\CTFAK2.0\Interface\CTFAK. Cli\Program.cs:line 180`

The game is 'Ultra Fight Da! Kyanta 2'. I have seen some issues that may be cropping up due to language characters, so I will not that the game does contain Japanese characters in its files (at least, the ones observable with Source Explorer, which reads the game fine disregarding the latest prerelease, where it also crashes.)

**Comment by AITYunivers** [comment] 2023-10-10 07:56
Duplicate of #62

**Closed by AITYunivers** 2023-10-10 07:56 UTC
