### ISSUE TITLE
.dat error

### ISSUE THREAD

**Issue by pukpuksrenk** [CTFAK/CTFAK2.0#88] opened 2023-11-05 19:51 UTC
![image](https://github.com/CTFAK/CTFAK2.0/assets/149963061/69b43f2f-8434-470d-926b-5922ba53782e)
i tried to decompile .dat file and got error

**Comment by AITYunivers** [comment] 2023-11-05 19:53
Duplicate of #62

**Closed by AITYunivers** 2023-11-05 19:53 UTC
