### ISSUE TITLE
I get this error when I try to decompile The Escape To Freddy's: Reborn

### ISSUE THREAD

**Issue by Wario3493** [CTFAK/CTFAK2.0#60] opened 2023-07-21 03:14 UTC
<img width="676" alt="teeareteeef" src="https://github.com/CTFAK/CTFAK2.0/assets/130720837/268599da-e1f2-49b6-a19c-ad6b146b6953">

**Comment by AITYunivers** [comment] 2023-07-21 03:15
Duplicate of #48

**Closed by AITYunivers** 2023-07-21 03:15 UTC
