### ISSUE TITLE
Hello. I found an issue. After CTFAK shows me those lines it instantly crashes.

### ISSUE THREAD

**Issue by MrBonBuns** [CTFAK/CTFAK2.0#70] opened 2023-08-13 13:23 UTC
![image](https://github.com/CTFAK/CTFAK2.0/assets/137725444/7261962e-d67f-432c-a130-827c829ba8f1)

**Comment by AITYunivers** [comment] 2023-10-07 06:32
Duplicate of #62

**Closed by AITYunivers** 2023-10-07 06:32 UTC
