### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by ptfk** [CTFAK/CTFAK2.0#68] opened 2023-08-10 04:57 UTC
![20230810125515](https://github.com/CTFAK/CTFAK2.0/assets/126636367/9c69cbb1-e62d-496b-89e5-66ff646a9e14)

**Comment by AITYunivers** [comment] 2023-08-10 05:00
So new that we already had it fixed for the next commit.

**Comment by AITYunivers** [comment] 2023-10-07 06:31
Duplicate of #62

**Closed by AITYunivers** 2023-10-07 06:31 UTC
Labels: 2.2
