### ISSUE TITLE
i can't use clickteam to open my mfa from fnaf world

### ISSUE THREAD

**Issue by glitchtrap99** [CTFAK/CTFAK2.0#69] opened 2023-08-10 20:04 UTC
after i use the tool and then open clickteam with the mfa it come up with an error can't load the frames.

**Comment by AITYunivers** [comment] 2023-08-10 20:05
cool

**Comment by AITYunivers** [comment] 2023-08-10 20:10
Most likely a duplicate of #50 reopen if not the case.

**Closed by AITYunivers** 2023-08-10 20:10 UTC
