### ISSUE TITLE
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')

### ISSUE THREAD

**Issue by MaxKotovov** [CTFAK/CTFAK2.0#72] opened 2023-08-16 17:03 UTC
![image](https://github.com/CTFAK/CTFAK2.0/assets/127125279/cfb6454b-a830-4d2b-abd6-5ea7b2e44fd8)
[Latest.log](https://github.com/CTFAK/CTFAK2.0/files/12361778/Latest.log)

**Comment by feiran-wang** [comment] 2023-09-25 02:09
same problem

**Comment by AITYunivers** [comment] 2023-10-07 06:33
Duplicate of #48

**Closed by AITYunivers** 2023-10-07 06:33 UTC
