### ISSUE TITLE
I get this error when I try decompiling Five Nights at Toy Alfredo, using the Defenitive Update.

### ISSUE THREAD

**Issue by Wario3493** [CTFAK/CTFAK2.0#58] opened 2023-07-18 05:57 UTC
<img width="662" alt="pea" src="https://github.com/CTFAK/CTFAK2.0/assets/130720837/eec6eb93-da8e-4f81-a54c-460149b9ee6a">

**Comment by AITYunivers** [comment] 2023-07-18 05:58
Duplicate of #48

**Closed by AITYunivers** 2023-07-18 05:58 UTC
